# Generated by Django 2.0.2 on 2018-03-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180226_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='iamge',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
