# Generated by Django 2.0.2 on 2018-03-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='iamge',
            new_name='image',
        ),
    ]
