# Generated by Django 2.0.2 on 2018-02-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
