# Generated by Django 2.0.2 on 2018-04-02 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180327_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
