# Generated by Django 2.0.2 on 2018-02-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('date_end', models.DateTimeField(null=True)),
            ],
        ),
    ]
