# Generated by Django 2.0.2 on 2018-02-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20180222_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
