# Generated by Django 2.0.2 on 2018-02-22 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180222_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='status_app',
            field=models.SmallIntegerField(choices=[('OnGoing', 'On-Going'), ('Finish', 'Finish')], default=1),
            preserve_default=False,
        ),
    ]
