# Generated by Django 2.0.2 on 2018-02-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_home_status_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='status_app',
            field=models.SmallIntegerField(choices=[(0, 'On-Going'), (1, 'Finish')]),
        ),
    ]
