# Generated by Django 2.0.2 on 2018-02-26 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180224_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'App Name'},
        ),
    ]
